export default {
  POSTS_LOADING_START: 'POSTS_LOADING_START',
  POSTS_LOADING_SUCCESS: 'POSTS_LOADING_SUCCESS',
  POSTS_LOADING_FINISHED: 'POSTS_LOADING_FINISHED',

  USERS_LOADING_START: 'USERS_LOADING_START',
  USERS_LOADING_SUCCESS: 'USERS_LOADING_SUCCESS',
  USERS_LOADING_FINISHED: 'USERS_LOADING_FINISHED',

  POST_LOADING_START: 'POST_LOADING_START',
  POST_LOADING_SUCCESS: 'POST_LOADING_SUCCESS',
  POST_LOADING_FINISHED: 'POST_LOADING_FINISHED'
}
